import cv2
import numpy as np
import collections
from typing import Dict, List, Tuple, Any, Set

class ZoneAnalytics:
    """
    Analyzes spatial interactions of tracked persons within pre-defined store zones.
    Calculates current occupancy, tracks dwell times, and visualizes zone overlays.
    """

    def __init__(self, zones: Dict[str, List[Tuple[int, int]]], frame_rate: float = 25.0):
        """
        Initialize the Zone Analytics engine.

        Args:
            zones (Dict[str, List[Tuple[int, int]]]): A dictionary mapping zone names 
                to a list of 4 (or more) (x, y) coordinates defining a polygon.
            frame_rate (float): The FPS of the video feed, used to calculate seconds from frame counts.
        """
        self.frame_rate = frame_rate
        
        # Convert list of tuples to numpy arrays for OpenCV polygon operations
        self.zones: Dict[str, np.ndarray] = {
            name: np.array(points, dtype=np.int32) for name, points in zones.items()
        }
        
        # State tracking
        # dwell_frames: dict mapping track_id -> dict(zone_name -> frame_count)
        self.dwell_frames: Dict[int, Dict[str, int]] = {}
        
        # Track unique visitors per zone: zone_name -> set(track_id)
        self.zone_visitors: Dict[str, Set[int]] = {name: set() for name in self.zones.keys()}
        
        # Current snapshot occupancy per zone
        self.current_zone_counts: Dict[str, int] = {name: 0 for name in self.zones.keys()}

        # Generate a distinct color palette for drawing up to 10 zones easily
        self._colors = [
            (255, 100, 100), (100, 255, 100), (100, 100, 255),
            (255, 255, 100), (255, 100, 255), (100, 255, 255),
            (255, 150, 50),  (50, 150, 255),  (150, 255, 50),
            (200, 200, 200)
        ]

    def update(self, tracks: List[Dict[str, Any]], current_frame: int) -> Dict[str, int]:
        """
        Takes the current active tracks, verifies their center points against defined zones,
        updates internal state for counts and dwell times, and returns the current occupancy.

        Args:
            tracks (List[Dict[str, Any]]): Track dictionaries generated by PersonTracker.
            current_frame (int): Current frame integer index (passed for logging/state if needed).

        Returns:
            Dict[str, int]: A dictionary mapping zone names to the current active track count inside it.
        """
        # Reset counts for the current frame
        current_counts = {name: 0 for name in self.zones.keys()}

        for track in tracks:
            track_id = track.get("track_id")
            cx, cy = track.get("center", (0, 0))

            if track_id is None:
                continue

            # Initialize dwell dictionary for new tracks
            if track_id not in self.dwell_frames:
                self.dwell_frames[track_id] = {name: 0 for name in self.zones.keys()}

            # Check if the center coordinates fall inside any zone polygon
            for zone_name, poly in self.zones.items():
                # measureMeasure >= 0 implies point is either strictly inside or on the edge of the contour
                is_inside = cv2.pointPolygonTest(poly, (float(cx), float(cy)), measureDist=False) >= 0
                
                if is_inside:
                    # Update snapshot count
                    current_counts[zone_name] += 1
                    # Update dwell time
                    self.dwell_frames[track_id][zone_name] += 1
                    # Register visitor
                    self.zone_visitors[zone_name].add(track_id)

        self.current_zone_counts = current_counts
        return current_counts

    def get_dwell_times(self) -> Dict[int, Dict[str, float]]:
        """
        Resolves total frame counts into tangible seconds based on the active frame_rate.
        
        Returns:
            Dict[int, Dict[str, float]]: A nested dictionary resolving track_id -> zone_name -> seconds.
        """
        dwell_seconds = {}
        for track_id, zone_data in self.dwell_frames.items():
            dwell_seconds[track_id] = {}
            for zone_name, frames in zone_data.items():
                # Only construct meaningful metrics actively touching zones
                if frames > 0:
                    dwell_seconds[track_id][zone_name] = float(frames) / self.frame_rate
                    
        return dwell_seconds

    def get_zone_summary(self) -> Dict[str, Dict[str, Any]]:
        """
        Rolls up historical tracking and current active status into a global analytical store summary.

        Returns:
            Dict[str, Dict[str, Any]]: Summary dictionary indexed by zone_name containing analytics.
        """
        summaries = {}
        all_dwell_times = self.get_dwell_times()

        for zone_name in self.zones.keys():
            # Extract out all non-zero dwell times for this specific zone across all tracked IDs
            zone_times = [
                times.get(zone_name, 0.0) 
                for tid, times in all_dwell_times.items() 
                if times.get(zone_name, 0.0) > 0.0
            ]
            
            avg_dwell = sum(zone_times) / len(zone_times) if zone_times else 0.0
            max_dwell = max(zone_times) if zone_times else 0.0
            total_visits = len(self.zone_visitors[zone_name])

            summaries[zone_name] = {
                "zone_name": zone_name,
                "current_count": self.current_zone_counts.get(zone_name, 0),
                "average_dwell_seconds": round(avg_dwell, 2),
                "max_dwell_seconds": round(max_dwell, 2),
                "total_visits": total_visits
            }

        return summaries

    def draw_zones(self, frame: np.ndarray) -> np.ndarray:
        """
        Overlays the zone polygons acting as semi-transparent maps, rendering labels
        and active occupancy counts textually above the footprint cleanly.

        Args:
            frame (np.ndarray): The raw OpenCV tracking frame output.

        Returns:
            np.ndarray: The finalized visually annotated frame with embedded mapping zones.
        """
        overlay = frame.copy()

        # Phase 1: Draw filled polygons onto the overlay image
        for i, (zone_name, poly) in enumerate(self.zones.items()):
            color = self._colors[i % len(self._colors)]
            cv2.fillPoly(overlay, [poly], color)

        # Alpha-blend the overlay back against the original frame to induce transparency mapping (Alpha=0.35)
        alpha = 0.35
        blended_frame = cv2.addWeighted(overlay, alpha, frame, 1 - alpha, 0)

        # Phase 2: Draw the hard labels above the blend so text doesn't fade equivalently
        for i, (zone_name, poly) in enumerate(self.zones.items()):
            color = self._colors[i % len(self._colors)]
            count = self.current_zone_counts.get(zone_name, 0)
            
            # Retrieve bounding-box bounds constraint logic around polygon drawing offset points
            x, y, w, h = cv2.boundingRect(poly)
            
            label = f"{zone_name} (Count: {count})"
            # Background rectangle for text readability
            (text_w, text_h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
            cv2.rectangle(blended_frame, (x, y - text_h - 10), (x + text_w, y + 5), (0, 0, 0), -1)
            
            # Place textual overlay bounding box securely above shapes
            cv2.putText(blended_frame, label, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

        return blended_frame


class QueueDetector:
    """
    Monitors a designated queuing area to detect long lines and estimate wait times.
    Triggers alerts when the number of people exceeds configured density thresholds.
    """

    def __init__(self, queue_zone: List[Tuple[int, int]], density_threshold: int = 3, frame_rate: float = 25.0):
        """
        Initialize the QueueDetector.

        Args:
            queue_zone (List[Tuple[int, int]]): A list of 4 (x, y) coordinates defining the queue bounded polygon.
            density_threshold (int): The number of people required to trigger a queue alert. Default is 3.
            frame_rate (float): FPS of the video feed used to calculate durations.
        """
        self.queue_zone = np.array(queue_zone, dtype=np.int32)
        self.density_threshold = density_threshold
        self.frame_rate = frame_rate
        
        self.current_count = 0
        self.is_queue_alert = False
        
        # State tracking for duration calculations
        self.queue_start_frame: int = -1
        self.current_queue_duration_frames: int = 0

    def update(self, tracks: List[Dict[str, Any]], current_frame: int) -> Dict[str, Any]:
        """
        Calculates occupancy within the queue zone and evaluates alert thresholds and wait time heuristics.

        Args:
            tracks (List[Dict[str, Any]]): Active tracked persons instances.
            current_frame (int): The active looping frame integer.

        Returns:
            Dict[str, Any]: Dictionary containing queue metrics and active alert status.
        """
        count = 0

        # Count persons physically bounded inside the queue polygon utilizing centers
        for track in tracks:
            cx, cy = track.get("center", (0, 0))
            if cv2.pointPolygonTest(self.queue_zone, (float(cx), float(cy)), measureDist=False) >= 0:
                count += 1

        self.current_count = count

        # Check if the queue limit is breached
        is_alert_now = self.current_count >= self.density_threshold

        if is_alert_now and not self.is_queue_alert:
            # A new queue event has started
            self.queue_start_frame = current_frame
            self.is_queue_alert = True
        elif not is_alert_now and self.is_queue_alert:
            # The queue has cleared
            self.is_queue_alert = False
            self.queue_start_frame = -1
            self.current_queue_duration_frames = 0

        # Update duration if we are currently in an active alert
        if self.is_queue_alert and self.queue_start_frame != -1:
            self.current_queue_duration_frames = current_frame - self.queue_start_frame

        duration_seconds = float(self.current_queue_duration_frames) / self.frame_rate

        # Simple heuristic: Assume each person in queue takes roughly 45 seconds to clear
        wait_estimate = float(self.current_count) * 45.0

        return {
            "people_in_queue": self.current_count,
            "is_queue_alert": self.is_queue_alert,
            "queue_duration_seconds": round(duration_seconds, 2),
            "average_wait_estimate_seconds": round(wait_estimate, 1)
        }

    def draw_queue_status(self, frame: np.ndarray) -> np.ndarray:
        """
        Draws the queue zone polygon and active status UI directly onto the video frame.

        Args:
            frame (np.ndarray): The raw OpenCV frame.

        Returns:
            np.ndarray: Blended frame overlaying queue polygon and visual text statuses.
        """
        overlay = frame.copy()
        
        # Color coding: Red if alert triggered, Green if normal
        color = (0, 0, 255) if self.is_queue_alert else (0, 255, 0)

        # Draw the physical queue footprint area
        cv2.fillPoly(overlay, [self.queue_zone], color)
        blended_frame = cv2.addWeighted(overlay, 0.35, frame, 0.65, 0)

        # Draw the boundary explicitly tight over the blend
        cv2.polylines(blended_frame, [self.queue_zone], isClosed=True, color=color, thickness=2)

        # Determine bounding configurations to float the text label logically 
        x, y, w, h = cv2.boundingRect(self.queue_zone)
        
        # Construct summary label
        status_text = "ALERT!" if self.is_queue_alert else "Normal"
        label = f"QUEUE {status_text} | Wait: {self.current_count * 45}s"
        
        (text_w, text_h), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.6, 2)
        cv2.rectangle(blended_frame, (x, y - text_h - 10), (x + text_w, y + 5), (0, 0, 0), -1)
        cv2.putText(blended_frame, label, (x, y - 5), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

        return blended_frame
