import os
import shutil
from pathlib import Path
from ultralytics import YOLO

# ==========================================
# RetailEye AI - YOLOv8 Training Script
# ==========================================

# 1. Configuration Dictionary
# Advanced training configuration specifically tuned for the RetailEye AI project
CONFIG = {
    # Basic params
    "model": "yolov8m.pt",
    "data": "/kaggle/working/merged_dataset/data.yaml",
    "epochs": 50,
    "imgsz": 640,
    "batch": 16,
    "workers": 4,
    
    # Save/Logging
    "project": "/kaggle/working/runs/detect",
    "name": "retaileye_training",
    "exist_ok": True,
    
    # Optimizer/Learning Rate
    "pretrained": True,
    "optimizer": "AdamW",
    "lr0": 0.001,
    "lrf": 0.01,
    "momentum": 0.937,
    "weight_decay": 0.0005,
    "warmup_epochs": 3,
    "cos_lr": True,
    "patience": 20, # Early stopping patience
    
    # Augmentations (to build robustness for CCTV feeds)
    "augment": True,
    "hsv_h": 0.015,
    "hsv_s": 0.7,
    "hsv_v": 0.4,
    "degrees": 5.0,
    "translate": 0.1,
    "scale": 0.5,
    "flipud": 0.0,
    "fliplr": 0.5,
    "mosaic": 1.0,
    "mixup": 0.1
}

# The target directory where we want to save our best weights for the final API
try:
    BASE_DIR = Path(__file__).resolve().parent.parent
except NameError:
    BASE_DIR = Path(os.getcwd())
    
FINAL_WEIGHTS_DIR = BASE_DIR / "models" / "weights"

def main():
    print("=== RetailEye AI: Advanced YOLOv8 Training ===")
    
    # Create final weights directory if needed
    FINAL_WEIGHTS_DIR.mkdir(parents=True, exist_ok=True)

    # 2. Initialize Model
    print(f"\n[1/4] Initializing model ({CONFIG['model']})...")
    model = YOLO(CONFIG["model"])

    # 3. Train the model using the strict CONFIG dictionary
    print("\n[2/4] Starting training with custom hyper-parameters...")
    try:
        model.train(**CONFIG)
    except Exception as e:
        print(f"\nTraining failed. Error details: {e}")
        return

    # 4. Final Validation & Results
    print("\n[3/4] Running standalone validation on the Best model...")
    # model.val() evaluates based on the best weights implicitly re-loaded under the hood
    # by ultralytics after training concludes
    val_results = model.val(data=CONFIG["data"], split="val")

    print("\n--- Training Results Summary ---")
    map50 = getattr(val_results.box, 'map50', 0.0)
    map50_95 = getattr(val_results.box, 'map', 0.0)
    print(f"mAP50:       {map50:.4f}")
    print(f"mAP50-95:    {map50_95:.4f}")
    print("Classification report data can be found in the results.csv generated by ultralytics.")

    # 5. Move the best weights
    print("\n[4/4] Saving best weights to designated directory...")
    source_weights = Path(CONFIG["project"]) / CONFIG["name"] / "weights" / "best.pt"
    target_weights = FINAL_WEIGHTS_DIR / "best_yolov8m.pt"

    if source_weights.exists():
        shutil.copy(str(source_weights), str(target_weights))
        print(f"✅ Successfully copied best weights to:\n   {target_weights}")
    else:
        print(f"⚠️ Warning: Could not find best weights at {source_weights}")
        
    print("\n=== Pipeline Complete ===")

if __name__ == "__main__":
    main()

